default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: maps_development

test:
  <<: *default
  database: maps_test

production:
  <<: *default
  database: maps_production
  username: maps
  password: <%= ENV['MAPS_DATABASE_PASSWORD'] %>